### ISSUE TITLE
FluidInstance causes a crash when outside of a development environment

### ISSUE THREAD

**Issue by raphydaphy** [Prospector/Silk#6]
Whenever a FluidInstance is created outside of a development environment, it crashes the game.

I wrote up a [super-simple mod](https://gist.github.com/raphydaphy/db1e8dda03cac2dac1594650f3c15e75) which demonstrates the issue when you run the command `/silk-test`. In a development environment, you will receive the message `It worked!` in chat, but otherwise the game crashes.

```
Encountered an unexpected exception java.lang.NoClassDefFoundError: net/minecraft/nbt/Tag 
at com.raphydaphy.silktest.SilkTest.lambda$null$3(SilkTest.java:18)
at com.raphydaphy.silktest.SilkTest$$Lambda$2388/1962762160.run(Unknown Source) 
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) 
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) 
at net.minecraft.class_2170.method_9249(class_2170.java:223) 
at net.minecraft.class_3244.method_14370(class_3244.java:1089) 
at net.minecraft.class_3244.method_12048(class_3244.java:1076) 
at net.minecraft.class_2797.method_12115(class_2797.java:37) 
at net.minecraft.class_2797.method_11054(class_2797.java:9) 
at net.minecraft.class_2600.method_11072(class_2600.java:15) 
at net.minecraft.class_2600$$Lambda$2825/632775869.run(Unknown Source) at net.minecraft.class_3738.run(class_3738.java:18) 
at net.minecraft.class_1255.method_18859(class_1255.java:122) 
at net.minecraft.class_4093.method_18859(class_4093.java:23) 
at net.minecraft.class_1255.method_16075(class_1255.java:101) 
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:693) 
at net.minecraft.class_1255.method_5383(class_1255.java:86) 
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:677) 
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) 
at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.ClassNotFoundException: net.minecraft.nbt.Tag at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
at net.fabricmc.loader.launch.knot.Knot$PatchingClassLoader.loadClass(Knot.java:222) 
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 20 more
```

**Comment by Prospector** [comment]
That's...weird. what version are you on and how hasn't anyone reported this before

**Comment by Prospector** [comment]
MC version I mean

**Comment by raphydaphy** [comment]
I'm on 19w11b, but I *think* i remember this happening on a previous version as well

**Comment by raphydaphy** [comment]
I guess noone has reported it because nobody bothers to test outside of dev environment

**Comment by LemmaEOF** [comment]
This looks like a mapping issue. It should be using `net/minecraft/class_2520` in prod instead of `net/minecraft/nbt/Tag`.

**Comment by raphydaphy** [comment]
To make sure this is actually caused by Silk and not a byproduct of something in my mod, I created an entirely separate mod and uploaded the jars in case you want to see the problem for yourself.

https://github.com/raphydaphy/SilkTest/releases/tag/v1.0

**Comment by raphydaphy** [comment]
despite this not working for me with builds from two different PC's as well as a jitpack and google cloud build, getting someone else to build the jar fixed the issue.. i don't know why but i guess it's resolved?
